#ifndef PINMAPS_HPP
#define PINMAPS_HPP

#ifndef ETH_PHY_CS
#define ETH_PHY_TYPE ETH_PHY_W5500
#define ETH_PHY_ADDR 1
#define ETH_PHY_CS 14
#define ETH_PHY_IRQ 10
#define ETH_PHY_RST 9
#define ETH_PHY_SPI_HOST SPI2_HOST
#define ETH_PHY_SPI_SCK 13
#define ETH_PHY_SPI_MISO 12
#define ETH_PHY_SPI_MOSI 11
#endif

#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_LEFTMOST 2
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_MIDDLE_LEFT 3
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_MIDDLE_RIGHT 4
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_RIGHTMOST 5

#define HW_MOTOR_LEFT_PWM_PIN 6
#define HW_MOTOR_RIGHT_PWM_PIN 7

#endif // PINMAPS_HPP