#pragma once

#ifndef ETH_PHY_CS
#define ETH_PHY_TYPE ETH_PHY_W5500
#define ETH_PHY_ADDR 1
#define ETH_PHY_CS 14
#define ETH_PHY_IRQ 10
#define ETH_PHY_RST 9
#define ETH_PHY_SPI_HOST SPI2_HOST
#define ETH_PHY_SPI_SCK 13
#define ETH_PHY_SPI_MISO 12
#define ETH_PHY_SPI_MOSI 11
#endif

#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_LEFTMOST 15
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_MIDDLE_LEFT 16
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_MIDDLE_RIGHT 17
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_RIGHTMOST 18

#define HW_MOTOR_LEFT_PWM_PIN 33
#define HW_MOTOR_RIGHT_PWM_PIN 34

// HUB75 LED Matrix Display pins
#define HW_DISPLAY_R1_PIN  42
#define HW_DISPLAY_G1_PIN  41
#define HW_DISPLAY_B1_PIN  40
#define HW_DISPLAY_R2_PIN  38
#define HW_DISPLAY_G2_PIN  39
#define HW_DISPLAY_B2_PIN  37
#define HW_DISPLAY_A_PIN   45
#define HW_DISPLAY_B_PIN   36
#define HW_DISPLAY_C_PIN   48
#define HW_DISPLAY_D_PIN   35
#define HW_DISPLAY_E_PIN   21
#define HW_DISPLAY_LAT_PIN 47
#define HW_DISPLAY_OE_PIN  46
#define HW_DISPLAY_CLK_PIN 2