#pragma once

#ifndef ETH_PHY_CS
#define ETH_PHY_TYPE ETH_PHY_W5500
#define ETH_PHY_ADDR 1
#define ETH_PHY_CS 14
#define ETH_PHY_IRQ 10
#define ETH_PHY_RST 9
#define ETH_PHY_SPI_HOST SPI2_HOST
#define ETH_PHY_SPI_SCK 13
#define ETH_PHY_SPI_MISO 12
#define ETH_PHY_SPI_MOSI 11
#endif

#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_LEFTMOST 15
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_MIDDLE_LEFT 16
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_MIDDLE_RIGHT 17
#define HW_SCORING_BREAK_BEAM_SENSOR_PIN_RIGHTMOST 18

#define HW_MOTOR_LEFT_PWM_PIN 33
#define HW_MOTOR_RIGHT_PWM_PIN 34